accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 100
benchmark: null
check_val_every_n_epoch: 1
checkpoint_callback: null
classify: organ_tissue
classify_dim: 24
data_path: !!python/object/apply:pathlib.PosixPath
- /
- scratch
- wconnell
- pretrain-gex
- datasets
- tabula-sapiens
- otf-prepro
- TabulaSapiens
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
dim_feedforward: 2048
dropout: 0.0
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
flush_logs_every_n_steps: null
frac: 0.15
gpus: 0,1,2,3
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
learning_rate: 0.0003
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
log_gpu_memory: null
logger: true
logs: !!python/object/apply:pathlib.PosixPath
- ..
- data
- models
max_epochs: 300
max_steps: -1
max_time: null
min_epochs: 50
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
name: classify-tissue-fixed
nhead: 4
num_layers: 1
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 6
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
query_dim: 4
query_len: 128
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seq_dim: 4
seq_len: 19067
stochastic_weight_avg: false
strategy: ddp
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
warmup_steps: 500
weight_decay: 1.0e-05
weights_save_path: null
weights_summary: top
